### ISSUE TITLE
publishedAt must be in the past.

### ISSUE THREAD

**Issue by leotulipan** [Medium/medium-wordpress-plugin#60]
WP 4.4 (German) with latest medium from the wp.org repo

- Log in as Admin
- Edit a Post of another user (that has a medium token)
- click Update
- I got the Error "Medium Error: If specified, publishedAt must be in the past. (2014)"

This might be a Timezone thing, as the post was about 15 minutes old, but the blog is setup to the CET (European) Timezone

**Comment by raumzeit77** [comment]
I have the exact same problem, but also with posts from my won account (admin). My timezone is set to Berlin.

**Comment by huckphin** [comment]
Thanks for reporting this issue. This is something that I can take a look at.

**Comment by chiwaili** [comment]
+1
I've been having the same issue for sometime now too. Currently in London, also had it in Hong Kong over a month ago

**Comment by serkanemir** [comment]
I've been having the same issue for sometime now too. Currently in Istanbul, Turkey. serkanemir.com

**Comment by huckphin** [comment]
If you upgrade to the latest version of the [Medium Wordpress plugin (1.2)](https://wordpress.org/plugins/medium/) it will now work correctly. Our backend also accounts for this properly by adjusting the date.

**Comment by raumzeit77** [comment]
sadly it still doesn't work. I've even re-installed the plugin.

**Comment by huckphin** [comment]
Reopening this. Will investigate, triage, and fix.

**Comment by pmuens** [comment]
Facing the same issue. Thanks for investigating!

**Comment by hkoivuneva** [comment]
I've also got this issue, unfortunately. Time zone is ACDT (UTC+10:30). Thank you in advance!

**Comment by huckphin** [comment]
The 1.2.2 WordPress plugin was just released, which will fix this issue.

**Comment by koffisani** [comment]
Medium Plugin v1.4.0 with the same error message 

> Medium Error: If specified, publishedAt must be in the past. (2014) .

WP 4.5.2.

**Comment by RajeshSource** [comment]
No luck ): 
Medium Error: If specified, publishedAt must be in the past. (2014) .

Blog was setup with Timezone to the "Newyork" and Medium plugin activated and published post which is published to medium also after 12-24hrs some how I am okay with the end result. 
I came to know in one post Timezone issue for hitting our European and Asian friends, so am from INDIA due to timezone issue I connected to USA through VPN and published another post which is not published to Medium. 
Is there any other possible way to make happen ?
WP Version 4.5.3, Medium Version 1.4.0
